// Code generated by cmd/cgo; DO NOT EDIT.

//line C:\Users\lucas\Desktop\auto-spammer\io_handler\go version\test_ffi\hello.go:1:1
package main

import _ "unsafe"
import "fmt"

//export hello
func hello() {
	fmt.Println("hello from go")
}
func main() {}
